- hosts: all
  tasks:
    - name: Install packages
      package: name={{ item }} state=latest
      with_items:
        - python-pip
        - screen
        - vim
        - telnet
        - tcpdump
        - traceroute
        - iperf3
        - nmap
        - ethtool
        - curl
        - git
        - dnsutils
